### ISSUE TITLE
make smaller the image using docker multi-stage build

### ISSUE THREAD

**Issue by hbakhtiyor** [yukinying/chrome-headless-browser-docker#16]
hi, did you have any chance to try it?

**Comment by yukinying** [comment]
I think it is not related. My understanding is that if a container is used in building the binary and installing the binary as well, then the image size can be reduced by separating the process into two. 

This repository does not build any binary. If it would, it would probably be done inside plain Travis CI environment rather than inside a container.

Ref: https://docs.docker.com/engine/userguide/eng-image/multistage-build/
