### ISSUE TITLE
Message: unknown error: an X display is required for keycode conversions, consider using Xvfb

### ISSUE THREAD

**Issue by Julienh** [yukinying/chrome-headless-browser-docker#19]
Hello,

Thanks for your container.

I use chrome-headless-browser-selenium container and I would like to fill a form with send_keys (in Python) but I have this error : 
`Message: unknown error: an X display is required for keycode conversions, consider using Xvfb
`
Is it possibile to install Xvfb please ?

Thank you

**Comment by Julienh** [comment]
It's a Chrome Headless problem sorry : https://bugs.chromium.org/p/chromedriver/issues/detail?id=1772#c12

**Comment by Julienh** [comment]
Is it possible to compile chrome and chromedriver with `use_ozone = true `?
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1772#c16

**Comment by yukinying** [comment]
This project repository only builds the docker images by installing the compiled chrome binary from Google. I think you may be referring to https://github.com/yukinying/chrome-headless-travis-build. But I am a bit skeptical to switch to use "ozone" because it just work. Instead I'd prefer waiting and observing the bug to see when a stable fix would be released.

**Comment by Julienh** [comment]
I understand, thank you for your work.

**Comment by yukinying** [comment]
Hi @Julienh, the chromedriver version has been upgraded to 2.31 and it should handle send_key. Please feel free to try it out. On the other hand, there is a report in headless-dev that 2.31 requires glibc 2.18. I haven't tested that but upgrading glibc should not be hard with docker.

**Comment by Julienh** [comment]
hi @yukinying , thank you I will try :)

**Comment by Julienh** [comment]
It's works now, thank you !
