### ISSUE TITLE
Debian stable is now bullseye

### ISSUE THREAD

**Issue by kierenevans** [yukinying/chrome-headless-browser-docker#45]
Hi!

We build a docker image from `yukinying/chrome-headless-browser` and install further packages, but `apt-get update` is failing with the following:
```
#5 0.362 Ign:1 http://security.debian.org/debian-security stable/updates InRelease
#5 0.362 Get:2 http://deb.debian.org/debian stable InRelease [113 kB]
#5 0.363 Err:3 http://security.debian.org/debian-security stable/updates Release
#5 0.363   404  Not Found [IP: 151.101.18.132 80]
#5 0.375 Get:4 http://deb.debian.org/debian stable-updates InRelease [36.8 kB]
#5 0.485 Get:5 http://deb.debian.org/debian stable/main amd64 Packages [8178 kB]
#5 1.582 Reading package lists...
#5 2.185 E: The repository 'http://security.debian.org/debian-security stable/updates Release' does not have a Release file.
```

Is it possible to push a rebuild of this docker image to docker hub based on the new `debian:stable-slim` which is bullseye and doesn't reference the 404 path in `/etc/apt/sources.list`?

Thanks!

**Comment by yukinying** [comment]
Yes, the docker image is intended to use the latest image. I would see if I can make this happen soon.

**Comment by yukinying** [comment]
It turns out the scheduled daily build on Travis was failing, as there was a migration from Travis-CI.org to Travis-CI.com, and I didn't realized that using Travis-CI.com would require a plan with OSS credit. I have triggered a build so the latest image you can pull should be pointing to the right `debian:stable-slim` image. If that does not work, please let me know.

**Comment by yukinying** [comment]
Please reopen if the latest image doesn't work. Thanks.

**Comment by kierenevans** [comment]
Thank you, working great :)
